### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by bluejmp2000** [Exomanz/MenuSaberColors#2]
it seems this mod on the new 1.21.0 version of beatsaber (1.0.2 version of the MenuSaberColors) completely breaks your game as it seems the floor; along with the notes, rise into unreachable heights. not sure if this is some poor taste in April fools joke or actual issue but it causes the game to be completely unplayable. aside from the base core mods mod assistant puts out im using
Camera2
MappingExtensions 
JDFixer
BetterSongSearch
FastFail
BetterSongList
and then clearly MenuSaberColors

**Comment by Exomanz** [comment]
The mod in question that is causing the map to rise to "unplayable heights" is actually JDFixer and not MenuSaberColors. JDFixer's April Fools joke can be disabled in its configuration. MenuSaberColors' April Fools joke is making the menu pointers rainbow.

**Comment by bluejmp2000** [comment]
i apologize, for some reason removing this mod had fixed it while JDFixer was still installed, but then after the 3rd map i noticed this issue starting again. i was about to go absolutely insane because of this, thank you for letting me know
